default_database: markdown

databases:
    - name: markdown
      provider: markdown
      config:
          path: ./playground/markdown/data

    - name: json
      provider: json
      config:
          path: ./playground/json/data

    - name: custom
      provider: customRoot1
      config:
          test: 123

    - name: folder
      provider: folder
      config:
          path: ./playground/folder/data
          id:
              strategy: date
              pattern: yyyy-MM-dd HH-mm-ss

    - name: folder-json
      provider: folder
      config:
          path: ./playground/folder-json/data
          format: json
