default_database: markdown

databases:
    - name: markdown
      provider: markdown
      config:
          path: ./playground/markdown/data

    - name: json
      provider: json
      config:
          path: ./playground/json/data

    - name: yaml 
      provider: yaml
      config:
          path: ./playground/yaml/data

    - name: yml 
      provider: yml
      config: 
          path: ./playground/yml/data
          

    - name: folder
      provider: folder
      config:
          path: ./playground/folder/data
          id:
              strategy: date
              pattern: yyyy-MM-dd HH-mm-ss

    - name: folder-json
      provider: folder
      config:
          path: ./playground/folder-json/data
          format: json

    - name: folder-yaml 
      provider: folder
      config: 
          path: ./playground/folder-yaml/data 
          format: yaml 

    - name: folder-yml 
      provider: folder
      config:
          path: ./playground/folder-yml/data 
          format: yml

