default_database: markdown

databases:
  - name: markdown 
    provider: markdown
    config:
      path: ./playground/markdown/data

  - name: custom 
    provider: customRoot1
    config:
        test: 123
